//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amil.DigitalSign
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDocument", Namespace="http://eval.cryptography/")]
    public partial class RequestDocument : object
    {
        
        private Amil.DigitalSign.RequestKeySelector KeySelectorField;
        
        private System.Nullable<System.DateTime> ReferenceTimeField;
        
        private string SignaturePolicyIdField;
        
        private string DocumentIdField;
        
        private System.Collections.Generic.List<Amil.DigitalSign.RequestSignature> SignatureListField;
        
        private string ContentField;
        
        private Amil.DigitalSign.ContentType ContentTypeField;
        
        private string XmlSchemaNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.RequestKeySelector KeySelector
        {
            get
            {
                return this.KeySelectorField;
            }
            set
            {
                this.KeySelectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> ReferenceTime
        {
            get
            {
                return this.ReferenceTimeField;
            }
            set
            {
                this.ReferenceTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SignaturePolicyId
        {
            get
            {
                return this.SignaturePolicyIdField;
            }
            set
            {
                this.SignaturePolicyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<Amil.DigitalSign.RequestSignature> SignatureList
        {
            get
            {
                return this.SignatureListField;
            }
            set
            {
                this.SignatureListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public Amil.DigitalSign.ContentType ContentType
        {
            get
            {
                return this.ContentTypeField;
            }
            set
            {
                this.ContentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string XmlSchemaName
        {
            get
            {
                return this.XmlSchemaNameField;
            }
            set
            {
                this.XmlSchemaNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestKeySelector", Namespace="http://eval.cryptography/")]
    public partial class RequestKeySelector : object
    {
        
        private Amil.DigitalSign.RequestKeyType TypeField;
        
        private string NameField;
        
        private Amil.DigitalSign.RequestSignerType SignerTypeField;
        
        private int SignerIndexField;
        
        private string CommitmentTypeField;
        
        private string XmlReferenceUriField;
        
        private Amil.DigitalSign.RequestAuthenticationToken AuthenticationTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Amil.DigitalSign.RequestKeyType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Amil.DigitalSign.RequestSignerType SignerType
        {
            get
            {
                return this.SignerTypeField;
            }
            set
            {
                this.SignerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SignerIndex
        {
            get
            {
                return this.SignerIndexField;
            }
            set
            {
                this.SignerIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CommitmentType
        {
            get
            {
                return this.CommitmentTypeField;
            }
            set
            {
                this.CommitmentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string XmlReferenceUri
        {
            get
            {
                return this.XmlReferenceUriField;
            }
            set
            {
                this.XmlReferenceUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Amil.DigitalSign.RequestAuthenticationToken AuthenticationToken
        {
            get
            {
                return this.AuthenticationTokenField;
            }
            set
            {
                this.AuthenticationTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestSignature", Namespace="http://eval.cryptography/")]
    public partial class RequestSignature : object
    {
        
        private string ValueField;
        
        private Amil.DigitalSign.RequestSignatureType TypeField;
        
        private string SignatureIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Amil.DigitalSign.RequestSignatureType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SignatureId
        {
            get
            {
                return this.SignatureIdField;
            }
            set
            {
                this.SignatureIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentType", Namespace="http://eval.cryptography/")]
    public enum ContentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Base64 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XML = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hash = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestAuthenticationToken", Namespace="http://eval.cryptography/")]
    public partial class RequestAuthenticationToken : object
    {
        
        private Amil.DigitalSign.RequestAuthenticationTokenType TypeField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Amil.DigitalSign.RequestAuthenticationTokenType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestKeyType", Namespace="http://eval.cryptography/")]
    public enum RequestKeyType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestSignerType", Namespace="http://eval.cryptography/")]
    public enum RequestSignerType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Signer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoSigner = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CounterSigner = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestAuthenticationTokenType", Namespace="http://eval.cryptography/")]
    public enum RequestAuthenticationTokenType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypePin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeCmsSignedAndEnveloped = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeCmsEnveloped = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TypeTicketAndPin = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestSignatureType", Namespace="http://eval.cryptography/")]
    public enum RequestSignatureType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attached = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Detached = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XMLDSigEnveloped = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XMLDSigEnveloping = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XMLDSigDetached = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://eval.cryptography/")]
    public partial class ResponseMessage : object
    {
        
        private Amil.DigitalSign.ResponseStatus MessageStatusField;
        
        private Amil.DigitalSign.ResponseOptionalOutput OptionalOutputField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.ResponseStatus MessageStatus
        {
            get
            {
                return this.MessageStatusField;
            }
            set
            {
                this.MessageStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.ResponseOptionalOutput OptionalOutput
        {
            get
            {
                return this.OptionalOutputField;
            }
            set
            {
                this.OptionalOutputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://eval.cryptography/")]
    public partial class ResponseStatus : object
    {
        
        private int StatusIdField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                this.StatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOptionalOutput", Namespace="http://eval.cryptography/")]
    public partial class ResponseOptionalOutput : object
    {
        
        private System.Collections.Generic.List<Amil.DigitalSign.ResponseDocument> DocumentListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<Amil.DigitalSign.ResponseDocument> DocumentList
        {
            get
            {
                return this.DocumentListField;
            }
            set
            {
                this.DocumentListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDocument", Namespace="http://eval.cryptography/")]
    public partial class ResponseDocument : object
    {
        
        private System.Collections.Generic.List<Amil.DigitalSign.ResponseSignature> SignatureListField;
        
        private string DocumentIdField;
        
        private string DocumentStatusField;
        
        private Amil.DigitalSign.ResponseStatus DocumentStatusExField;
        
        private Amil.DigitalSign.ResponseContent ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<Amil.DigitalSign.ResponseSignature> SignatureList
        {
            get
            {
                return this.SignatureListField;
            }
            set
            {
                this.SignatureListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocumentStatus
        {
            get
            {
                return this.DocumentStatusField;
            }
            set
            {
                this.DocumentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Amil.DigitalSign.ResponseStatus DocumentStatusEx
        {
            get
            {
                return this.DocumentStatusExField;
            }
            set
            {
                this.DocumentStatusExField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Amil.DigitalSign.ResponseContent Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContent", Namespace="http://eval.cryptography/")]
    public partial class ResponseContent : object
    {
        
        private string ValueField;
        
        private Amil.DigitalSign.ResponseContentType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Amil.DigitalSign.ResponseContentType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseSignature", Namespace="http://eval.cryptography/")]
    public partial class ResponseSignature : object
    {
        
        private Amil.DigitalSign.ResponseStatus StatusField;
        
        private Amil.DigitalSign.ResponseSignatureType TypeField;
        
        private System.Collections.Generic.List<Amil.DigitalSign.ResponseSigner> SignerListField;
        
        private string ValueField;
        
        private string SignatureIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.ResponseStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Amil.DigitalSign.ResponseSignatureType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Collections.Generic.List<Amil.DigitalSign.ResponseSigner> SignerList
        {
            get
            {
                return this.SignerListField;
            }
            set
            {
                this.SignerListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SignatureId
        {
            get
            {
                return this.SignatureIdField;
            }
            set
            {
                this.SignatureIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseSignatureType", Namespace="http://eval.cryptography/")]
    public enum ResponseSignatureType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attached = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Detached = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enveloped = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enveloping = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseSigner", Namespace="http://eval.cryptography/")]
    public partial class ResponseSigner : object
    {
        
        private string SubjectField;
        
        private string IssuerField;
        
        private string X509CertificateField;
        
        private string CorporateNameField;
        
        private string NISField;
        
        private string INSSField;
        
        private string TituloEleitorField;
        
        private string ZonaEleitoralField;
        
        private string SecaoField;
        
        private string LocalDoTituloField;
        
        private Amil.DigitalSign.ResponseOtherName ProfessionalIdField;
        
        private string DocumentNameField;
        
        private string RandomNonceField;
        
        private string SerialNumberField;
        
        private string CpfField;
        
        private string HashField;
        
        private string CnpjField;
        
        private string ValidFromField;
        
        private string ValidToField;
        
        private string CertificateTypeField;
        
        private string NameField;
        
        private string BirthDateField;
        
        private string RgField;
        
        private string RazaoSocialField;
        
        private string IcpBrasilField;
        
        private Amil.DigitalSign.ResponseCrl CrlField;
        
        private Amil.DigitalSign.ResponseOcsp OcspField;
        
        private string SigningTimeField;
        
        private Amil.DigitalSign.ResponseTimestamp TimestampField;
        
        private string SignerIdField;
        
        private Amil.DigitalSign.ResponseStatus SignerStatusField;
        
        private string RevocationStatusField;
        
        private System.Collections.Generic.List<Amil.DigitalSign.ResponseCertificate> ChainField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string X509Certificate
        {
            get
            {
                return this.X509CertificateField;
            }
            set
            {
                this.X509CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CorporateName
        {
            get
            {
                return this.CorporateNameField;
            }
            set
            {
                this.CorporateNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NIS
        {
            get
            {
                return this.NISField;
            }
            set
            {
                this.NISField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string INSS
        {
            get
            {
                return this.INSSField;
            }
            set
            {
                this.INSSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TituloEleitor
        {
            get
            {
                return this.TituloEleitorField;
            }
            set
            {
                this.TituloEleitorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ZonaEleitoral
        {
            get
            {
                return this.ZonaEleitoralField;
            }
            set
            {
                this.ZonaEleitoralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Secao
        {
            get
            {
                return this.SecaoField;
            }
            set
            {
                this.SecaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string LocalDoTitulo
        {
            get
            {
                return this.LocalDoTituloField;
            }
            set
            {
                this.LocalDoTituloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Amil.DigitalSign.ResponseOtherName ProfessionalId
        {
            get
            {
                return this.ProfessionalIdField;
            }
            set
            {
                this.ProfessionalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string RandomNonce
        {
            get
            {
                return this.RandomNonceField;
            }
            set
            {
                this.RandomNonceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SerialNumber
        {
            get
            {
                return this.SerialNumberField;
            }
            set
            {
                this.SerialNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Cpf
        {
            get
            {
                return this.CpfField;
            }
            set
            {
                this.CpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Hash
        {
            get
            {
                return this.HashField;
            }
            set
            {
                this.HashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Cnpj
        {
            get
            {
                return this.CnpjField;
            }
            set
            {
                this.CnpjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string CertificateType
        {
            get
            {
                return this.CertificateTypeField;
            }
            set
            {
                this.CertificateTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Rg
        {
            get
            {
                return this.RgField;
            }
            set
            {
                this.RgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string RazaoSocial
        {
            get
            {
                return this.RazaoSocialField;
            }
            set
            {
                this.RazaoSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string IcpBrasil
        {
            get
            {
                return this.IcpBrasilField;
            }
            set
            {
                this.IcpBrasilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public Amil.DigitalSign.ResponseCrl Crl
        {
            get
            {
                return this.CrlField;
            }
            set
            {
                this.CrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public Amil.DigitalSign.ResponseOcsp Ocsp
        {
            get
            {
                return this.OcspField;
            }
            set
            {
                this.OcspField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string SigningTime
        {
            get
            {
                return this.SigningTimeField;
            }
            set
            {
                this.SigningTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public Amil.DigitalSign.ResponseTimestamp Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string SignerId
        {
            get
            {
                return this.SignerIdField;
            }
            set
            {
                this.SignerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public Amil.DigitalSign.ResponseStatus SignerStatus
        {
            get
            {
                return this.SignerStatusField;
            }
            set
            {
                this.SignerStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string RevocationStatus
        {
            get
            {
                return this.RevocationStatusField;
            }
            set
            {
                this.RevocationStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public System.Collections.Generic.List<Amil.DigitalSign.ResponseCertificate> Chain
        {
            get
            {
                return this.ChainField;
            }
            set
            {
                this.ChainField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOtherName", Namespace="http://eval.cryptography/")]
    public partial class ResponseOtherName : object
    {
        
        private string TypeIdField;
        
        private string ValueField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TypeId
        {
            get
            {
                return this.TypeIdField;
            }
            set
            {
                this.TypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCrl", Namespace="http://eval.cryptography/")]
    public partial class ResponseCrl : object
    {
        
        private string EffectiveDateField;
        
        private string NextUpdateField;
        
        private string UrlField;
        
        private string IssuerField;
        
        private string X509CrlField;
        
        private string VersionField;
        
        private string NumberField;
        
        private string RevocationDateField;
        
        private string ReasonCodeField;
        
        private string InvalidityDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NextUpdate
        {
            get
            {
                return this.NextUpdateField;
            }
            set
            {
                this.NextUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string X509Crl
        {
            get
            {
                return this.X509CrlField;
            }
            set
            {
                this.X509CrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RevocationDate
        {
            get
            {
                return this.RevocationDateField;
            }
            set
            {
                this.RevocationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string InvalidityDate
        {
            get
            {
                return this.InvalidityDateField;
            }
            set
            {
                this.InvalidityDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOcsp", Namespace="http://eval.cryptography/")]
    public partial class ResponseOcsp : object
    {
        
        private string StatusField;
        
        private string EffectiveDateField;
        
        private string IssuerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseTimestamp", Namespace="http://eval.cryptography/")]
    public partial class ResponseTimestamp : object
    {
        
        private string VersionField;
        
        private string GeneralTimeField;
        
        private string CertificateTsaField;
        
        private System.Collections.Generic.List<Amil.DigitalSign.ResponseCertificate> ChainField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GeneralTime
        {
            get
            {
                return this.GeneralTimeField;
            }
            set
            {
                this.GeneralTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CertificateTsa
        {
            get
            {
                return this.CertificateTsaField;
            }
            set
            {
                this.CertificateTsaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<Amil.DigitalSign.ResponseCertificate> Chain
        {
            get
            {
                return this.ChainField;
            }
            set
            {
                this.ChainField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCertificate", Namespace="http://eval.cryptography/")]
    public partial class ResponseCertificate : object
    {
        
        private string SerialField;
        
        private string SubjectDNField;
        
        private string IssuerDNField;
        
        private string ValidFromField;
        
        private string ValidToField;
        
        private string VersionField;
        
        private string SignatureAlgorithmField;
        
        private string PublicKeyField;
        
        private string RevocationStatusField;
        
        private string TypeField;
        
        private Amil.DigitalSign.ResponseCrl CrlField;
        
        private Amil.DigitalSign.ResponseOcsp OcspField;
        
        private System.Collections.Generic.List<Amil.DigitalSign.ResponseCertificateExtension> ExtensionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubjectDN
        {
            get
            {
                return this.SubjectDNField;
            }
            set
            {
                this.SubjectDNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IssuerDN
        {
            get
            {
                return this.IssuerDNField;
            }
            set
            {
                this.IssuerDNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SignatureAlgorithm
        {
            get
            {
                return this.SignatureAlgorithmField;
            }
            set
            {
                this.SignatureAlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PublicKey
        {
            get
            {
                return this.PublicKeyField;
            }
            set
            {
                this.PublicKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string RevocationStatus
        {
            get
            {
                return this.RevocationStatusField;
            }
            set
            {
                this.RevocationStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Amil.DigitalSign.ResponseCrl Crl
        {
            get
            {
                return this.CrlField;
            }
            set
            {
                this.CrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public Amil.DigitalSign.ResponseOcsp Ocsp
        {
            get
            {
                return this.OcspField;
            }
            set
            {
                this.OcspField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public System.Collections.Generic.List<Amil.DigitalSign.ResponseCertificateExtension> Extensions
        {
            get
            {
                return this.ExtensionsField;
            }
            set
            {
                this.ExtensionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCertificateExtension", Namespace="http://eval.cryptography/")]
    public partial class ResponseCertificateExtension : object
    {
        
        private string ObjectIdentifierField;
        
        private string FriendlyNameField;
        
        private string ValueField;
        
        private bool IsCriticalField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ObjectIdentifier
        {
            get
            {
                return this.ObjectIdentifierField;
            }
            set
            {
                this.ObjectIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FriendlyName
        {
            get
            {
                return this.FriendlyNameField;
            }
            set
            {
                this.FriendlyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsCritical
        {
            get
            {
                return this.IsCriticalField;
            }
            set
            {
                this.IsCriticalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseContentType", Namespace="http://eval.cryptography/")]
    public enum ResponseContentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentTypeData = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentTypeSignedData = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseTicket", Namespace="http://eval.cryptography/")]
    public partial class ResponseTicket : object
    {
        
        private Amil.DigitalSign.RequestAuthenticationToken AuthenticationTokenField;
        
        private Amil.DigitalSign.ResponseStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.RequestAuthenticationToken AuthenticationToken
        {
            get
            {
                return this.AuthenticationTokenField;
            }
            set
            {
                this.AuthenticationTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.ResponseStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseGenerateDigest", Namespace="http://eval.cryptography/")]
    public partial class ResponseGenerateDigest : object
    {
        
        private Amil.DigitalSign.ResponseStatus StatusField;
        
        private Amil.DigitalSign.ResponseDigest DigestField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.ResponseStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Amil.DigitalSign.ResponseDigest Digest
        {
            get
            {
                return this.DigestField;
            }
            set
            {
                this.DigestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDigest", Namespace="http://eval.cryptography/")]
    public partial class ResponseDigest : object
    {
        
        private string AlgorithmField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Algorithm
        {
            get
            {
                return this.AlgorithmField;
            }
            set
            {
                this.AlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseGetDigestAlgorithm", Namespace="http://eval.cryptography/")]
    public partial class ResponseGetDigestAlgorithm : object
    {
        
        private Amil.DigitalSign.ResponseStatus StatusField;
        
        private string AlgorithmField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Amil.DigitalSign.ResponseStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Algorithm
        {
            get
            {
                return this.AlgorithmField;
            }
            set
            {
                this.AlgorithmField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://eval.cryptography/", ConfigurationName="Amil.DigitalSign.WSCryptoServerSoap")]
    public interface WSCryptoServerSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eval.cryptography/Sign", ReplyAction="*")]
        System.Threading.Tasks.Task<Amil.DigitalSign.SignResponse> SignAsync(Amil.DigitalSign.SignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eval.cryptography/Verify", ReplyAction="*")]
        System.Threading.Tasks.Task<Amil.DigitalSign.VerifyResponse> VerifyAsync(Amil.DigitalSign.VerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eval.cryptography/GenerateTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<Amil.DigitalSign.GenerateTicketResponse> GenerateTicketAsync(Amil.DigitalSign.GenerateTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eval.cryptography/GenerateDigest", ReplyAction="*")]
        System.Threading.Tasks.Task<Amil.DigitalSign.GenerateDigestResponse> GenerateDigestAsync(Amil.DigitalSign.GenerateDigestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://eval.cryptography/GetDigestAlgorithm", ReplyAction="*")]
        System.Threading.Tasks.Task<Amil.DigitalSign.GetDigestAlgorithmResponse> GetDigestAlgorithmAsync(Amil.DigitalSign.GetDigestAlgorithmRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sign", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.SignRequestBody Body;
        
        public SignRequest()
        {
        }
        
        public SignRequest(Amil.DigitalSign.SignRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class SignRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profileId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string todoPolicyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string responsePolicyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<Amil.DigitalSign.RequestDocument> documentList;
        
        public SignRequestBody()
        {
        }
        
        public SignRequestBody(string profileId, string todoPolicyName, string responsePolicyName, System.Collections.Generic.List<Amil.DigitalSign.RequestDocument> documentList)
        {
            this.profileId = profileId;
            this.todoPolicyName = todoPolicyName;
            this.responsePolicyName = responsePolicyName;
            this.documentList = documentList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignResponse", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.SignResponseBody Body;
        
        public SignResponse()
        {
        }
        
        public SignResponse(Amil.DigitalSign.SignResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class SignResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Amil.DigitalSign.ResponseMessage SignResult;
        
        public SignResponseBody()
        {
        }
        
        public SignResponseBody(Amil.DigitalSign.ResponseMessage SignResult)
        {
            this.SignResult = SignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.VerifyRequestBody Body;
        
        public VerifyRequest()
        {
        }
        
        public VerifyRequest(Amil.DigitalSign.VerifyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class VerifyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profileId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string todoPolicyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string responsePolicyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Collections.Generic.List<Amil.DigitalSign.RequestDocument> documentList;
        
        public VerifyRequestBody()
        {
        }
        
        public VerifyRequestBody(string profileId, string todoPolicyName, string responsePolicyName, System.Collections.Generic.List<Amil.DigitalSign.RequestDocument> documentList)
        {
            this.profileId = profileId;
            this.todoPolicyName = todoPolicyName;
            this.responsePolicyName = responsePolicyName;
            this.documentList = documentList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyResponse", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.VerifyResponseBody Body;
        
        public VerifyResponse()
        {
        }
        
        public VerifyResponse(Amil.DigitalSign.VerifyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class VerifyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Amil.DigitalSign.ResponseMessage VerifyResult;
        
        public VerifyResponseBody()
        {
        }
        
        public VerifyResponseBody(Amil.DigitalSign.ResponseMessage VerifyResult)
        {
            this.VerifyResult = VerifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateTicketRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateTicket", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.GenerateTicketRequestBody Body;
        
        public GenerateTicketRequest()
        {
        }
        
        public GenerateTicketRequest(Amil.DigitalSign.GenerateTicketRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class GenerateTicketRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string profileId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string keySelectorName;
        
        public GenerateTicketRequestBody()
        {
        }
        
        public GenerateTicketRequestBody(string profileId, string keySelectorName)
        {
            this.profileId = profileId;
            this.keySelectorName = keySelectorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateTicketResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateTicketResponse", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.GenerateTicketResponseBody Body;
        
        public GenerateTicketResponse()
        {
        }
        
        public GenerateTicketResponse(Amil.DigitalSign.GenerateTicketResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class GenerateTicketResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Amil.DigitalSign.ResponseTicket GenerateTicketResult;
        
        public GenerateTicketResponseBody()
        {
        }
        
        public GenerateTicketResponseBody(Amil.DigitalSign.ResponseTicket GenerateTicketResult)
        {
            this.GenerateTicketResult = GenerateTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateDigestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateDigest", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.GenerateDigestRequestBody Body;
        
        public GenerateDigestRequest()
        {
        }
        
        public GenerateDigestRequest(Amil.DigitalSign.GenerateDigestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class GenerateDigestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string algorithm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public GenerateDigestRequestBody()
        {
        }
        
        public GenerateDigestRequestBody(string algorithm, string content)
        {
            this.algorithm = algorithm;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateDigestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateDigestResponse", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.GenerateDigestResponseBody Body;
        
        public GenerateDigestResponse()
        {
        }
        
        public GenerateDigestResponse(Amil.DigitalSign.GenerateDigestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class GenerateDigestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Amil.DigitalSign.ResponseGenerateDigest GenerateDigestResult;
        
        public GenerateDigestResponseBody()
        {
        }
        
        public GenerateDigestResponseBody(Amil.DigitalSign.ResponseGenerateDigest GenerateDigestResult)
        {
            this.GenerateDigestResult = GenerateDigestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigestAlgorithmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigestAlgorithm", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.GetDigestAlgorithmRequestBody Body;
        
        public GetDigestAlgorithmRequest()
        {
        }
        
        public GetDigestAlgorithmRequest(Amil.DigitalSign.GetDigestAlgorithmRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class GetDigestAlgorithmRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string todoPolicyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string alias;
        
        public GetDigestAlgorithmRequestBody()
        {
        }
        
        public GetDigestAlgorithmRequestBody(string todoPolicyName, string alias)
        {
            this.todoPolicyName = todoPolicyName;
            this.alias = alias;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigestAlgorithmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigestAlgorithmResponse", Namespace="http://eval.cryptography/", Order=0)]
        public Amil.DigitalSign.GetDigestAlgorithmResponseBody Body;
        
        public GetDigestAlgorithmResponse()
        {
        }
        
        public GetDigestAlgorithmResponse(Amil.DigitalSign.GetDigestAlgorithmResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://eval.cryptography/")]
    public partial class GetDigestAlgorithmResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Amil.DigitalSign.ResponseGetDigestAlgorithm GetDigestAlgorithmResult;
        
        public GetDigestAlgorithmResponseBody()
        {
        }
        
        public GetDigestAlgorithmResponseBody(Amil.DigitalSign.ResponseGetDigestAlgorithm GetDigestAlgorithmResult)
        {
            this.GetDigestAlgorithmResult = GetDigestAlgorithmResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface WSCryptoServerSoapChannel : Amil.DigitalSign.WSCryptoServerSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class WSCryptoServerSoapClient : System.ServiceModel.ClientBase<Amil.DigitalSign.WSCryptoServerSoap>, Amil.DigitalSign.WSCryptoServerSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSCryptoServerSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSCryptoServerSoapClient.GetBindingForEndpoint(endpointConfiguration), WSCryptoServerSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCryptoServerSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSCryptoServerSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCryptoServerSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSCryptoServerSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCryptoServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Amil.DigitalSign.SignResponse> SignAsync(Amil.DigitalSign.SignRequest request)
        {
            return base.Channel.SignAsync(request);
        }
        
        public System.Threading.Tasks.Task<Amil.DigitalSign.VerifyResponse> VerifyAsync(Amil.DigitalSign.VerifyRequest request)
        {
            return base.Channel.VerifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Amil.DigitalSign.GenerateTicketResponse> GenerateTicketAsync(Amil.DigitalSign.GenerateTicketRequest request)
        {
            return base.Channel.GenerateTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Amil.DigitalSign.GenerateDigestResponse> GenerateDigestAsync(Amil.DigitalSign.GenerateDigestRequest request)
        {
            return base.Channel.GenerateDigestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Amil.DigitalSign.GetDigestAlgorithmResponse> GetDigestAlgorithmAsync(Amil.DigitalSign.GetDigestAlgorithmRequest request)
        {
            return base.Channel.GetDigestAlgorithmAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSCryptoServerSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSCryptoServerSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSCryptoServerSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.madics.com.br/WSCryptoServer/WSCryptoServer.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSCryptoServerSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://amlapse1sp0738:8088/mockWSCryptoServerSoap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSCryptoServerSoap12,
            
            WSCryptoServerSoap,
        }
    }
}
